# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_gui.py'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import traceback

from PyQt5.QtWidgets import QMessageBox
from pyqt5_plugins.examplebutton import QtWidgets

from measure_velovity_gui.ui.main_window_ui import Ui_MainWindow
from measure_velovity_gui.velocity_measurer import VelocityMeasure

video_measurer = VelocityMeasure()

def handle_exception(exc_type, exc_value, exc_traceback):
    # 构建奔溃信息
    exception_str = "".join(
        traceback.format_exception(exc_type, exc_value, exc_traceback)
    )

    print(exception_str)

    # 弹出对话框显示奔溃信息
    msg_box = QMessageBox()
    msg_box.setIcon(QMessageBox.Critical)
    msg_box.setWindowTitle("奔溃信息")
    msg_box.setText("应用程序遇到了一个错误。")
    msg_box.setDetailedText(exception_str)
    msg_box.exec_()


if __name__ == "__main__":
    import sys

    # 设置异常处理钩子
    sys.excepthook = handle_exception

    my_app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.bindListener(MainWindow)
    MainWindow.show()
    sys.exit(my_app.exec_())
